version: '3.8'
services:
  db:
    image: postgres:alpine
    # image: cgr.dev/chainguard/postgres
    # privileged: true
    restart: always
    environment:
      - POSTGRES_USER=kiddybank
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DATABASE=kiddybank
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data:z
volumes:
  db: